### ISSUE TITLE
CEF Binaries (libcef)

### ISSUE THREAD

**Issue by czenzel** [SethGibson/CEF_01#3]
Hello everyone,

I was wondering if you can help me out. I am trying to investigate on creating a fork of this repository and implementing the latest CefGlue and CEF binaries into Unity 3D.

When I tried to use binaries I found from Spotify's servers Unity says they are incompatible "DllNotFound" due to dependencies.

Does anyone have a working list of CEF binaries I can use for the Windows x86/x86_64 platform to use with CEF_01?

I am trying to build a project for HoloLens with the CEF browser.

Thanks
Chris Zenzel

**Comment by SethGibson** [comment]
My recommendation if you need a production ready solution would actually be to grab Zen Fulcrum's browser plugin from the Asset Store:
https://www.assetstore.unity3d.com/en/#!/content/55459

Otherwise, you might have to build your own binaries, which is a bit of a daunting task, but not impossible. I haven't tried using the binaries from Spotify or Adobe, so I'm not sure what is or isn't in their buildchain.

**Comment by czenzel** [comment]
I was able to upgrade the binaries with the help of CEFGlue's Bitbucket. Somebody had provided a link to their personal NuGet which contained binaries for CEF that helped. I am receiving issue #2 now and I also sent a copy to Unity 3D to help with the issue.

I am just experimenting with this (not for production). The asset you provided looks great, but it states it does not support the HoloLens.

There seems to be an issue with Spotify's binaries for the release that matches with CefGlue's latest version. Maybe it was a nightly build / alpha build issue.

Thank you for your help @SethGibson. I close this issue and keep issue #2 updated if I hear anything from Unity myself.

**Comment by SethGibson** [comment]
Awesome, thanks! And definitely keep filing issues related to this with Unity, I know a few other folks have, and it'd be great if they step up and add their own browser component like Unreal or other engines.
